import { StyleSheet } from "react-native";
import { heightPercentageToDP } from "react-native-responsive-screen";
import AppStyles from "app/config/styles";

const styles = StyleSheet.create({
  container: {
    width: "95%",
    borderRadius: 10,
    paddingTop: 10,
    flexWrap:"wrap",
    paddingBottom:20,
    backgroundColor: AppStyles.color.COLOR_WHITE,
    alignSelf: "center",
  },
  tickContainer: {
    width: "90%",
    borderRadius: 10,
    flexDirection: "row",
    marginTop: 10,
    height: heightPercentageToDP(7.5),
    backgroundColor: AppStyles.color.COLOR_SMOKE_WHITE,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  imgTick: { width: 33, height: 33, marginLeft: 15 },
  tripContainer: {
    width: "85%",
    height: "100%",
    flexDirection: "column",
    justifyContent: "center",
  },
  completeText: {
    fontFamily: AppStyles.fonts.SF_FONT_MEDIUM,
    paddingLeft: 14,
    color: AppStyles.color.COLOR_BLACK,
    fontSize: 15,
  },
  completeMessage: {
    fontFamily: AppStyles.fonts.SF_FONT_MEDIUM,
    paddingLeft: 14,
    color: AppStyles.color.COLOR_GREY_BG,
    fontSize: 12,
    paddingBottom: 2,
  },
  distanceContainer: {
    width: "100%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  distanceInnerContainer: {
    width: "30%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  kmText: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_GREY_DARK,
    fontSize: heightPercentageToDP(1.6),
    paddingLeft: 20,
  },
  kmContainer: {
    width: "65%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  actualKmText: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    textAlign: "right",
    color: AppStyles.color.COLOR_BLACK,
    fontSize: heightPercentageToDP(1.61),
    paddingLeft: 20,
  },
  timeContainer: {
    width: "100%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  timeInnerContainer: {
    width: "30%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  timeTaken: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_GREY,
    fontSize: heightPercentageToDP(1.6),
    paddingLeft: 20,
  },
  timeValueContainer: {
    width: "65%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  timeValue: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    textAlign: "right",
    color: AppStyles.color.COLOR_BLACK,
    fontSize: heightPercentageToDP(1.61),
    paddingLeft: 20,
  },
  priceContainer: {
    width: "100%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  priceInnnerContainer: {
    width: "30%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  priceText: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_GREY_DARK,
    fontSize: heightPercentageToDP(1.6),
    paddingLeft: 20,
  },
  paymentContainer: {
    width: "65%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  payAmountContainer: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_BLACK,
    fontSize: heightPercentageToDP(1.6),
    paddingLeft: 20,
  },
  methodContainer: {
    width: "100%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  methodInnerContainer: {
    width: "35%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  methodText: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_GREY_DARK,
    fontSize: heightPercentageToDP(1.6),
    paddingLeft: 20,
  },
  typeContainer: {
    width: "60%",
    height: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  typeText: {
    fontFamily: AppStyles.fonts.SF_FONT_REGULAR,
    color: AppStyles.color.COLOR_BLACK,
    fontSize: heightPercentageToDP(1.6),
    paddingLeft: 20,
  },
  cardContainer: {
    width: 30,
    height: 18,
    marginLeft: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: AppStyles.color.COLOR_SOLITUDE,
    justifyContent: "center",
  },
  imgCard: { width: 16, height: 16, alignSelf: "center" },
  locationContainer: {
    width: "95%",
    flexDirection: "row",
    height: heightPercentageToDP(20),
    marginTop: 10,
    alignSelf: "center",
  },
  locationInnerContainer: {
    width: "10%",
    height: "100%",
    backgroundColor: AppStyles.color.COLOR_WHITE,
    alignItems: "center",
  },
  bigDot: {
    width: 7,
    height: 7,
    marginTop: 15,
    backgroundColor: AppStyles.color.COLOR_GLACIER,
    borderRadius: 10,
  },
  smallDot: {
    width: 3,
    height: 3,
    marginTop: 5,
    backgroundColor: AppStyles.color.COLOR_LIGHT_GREY,
    borderRadius: 10,
  },
  mediumDot: {
    width: 7,
    height: 7,
    marginTop: 8,
    backgroundColor: AppStyles.color.COLOR_CASABLANCA,
    borderRadius: 10,
  },
  starContainer: {
    width: "90%",
    height: heightPercentageToDP(12),
    marginTop: 9,
    flexDirection: "column",
    marginLeft: 0,
  },
  fromContainer: {
    width: "100%",
    height: heightPercentageToDP(10.5),
    flexDirection: "column",
    marginLeft: 0,
  },
  fromText: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_GREY_PROFILE,
    fontSize: heightPercentageToDP(1.7),
  },
  startLocationText: {
    fontFamily: AppStyles.fonts.SF_FONT_MEDIUM,
    color: AppStyles.color.COLOR_BLACK,
    fontSize: heightPercentageToDP(1.6),
    marginTop: 2,
  },
  whereContainer: {
    width: "100%",
    height: heightPercentageToDP(6),
    flexDirection: "column",
    marginLeft: 0,
  },
  wherText: {
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_GREY_PROFILE,
    fontSize: heightPercentageToDP(1.7),
  },
  endLocationName: {
    fontFamily: AppStyles.fonts.SF_FONT_MEDIUM,
    color: AppStyles.color.COLOR_BLACK,
    fontSize: heightPercentageToDP(1.6),
    marginTop: 2,
  },
  doneContainer: {
    width: "85%",
    height: 50,
    alignSelf: "center",
    marginTop: 5,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  doneText: {
    width: "100%",
    alignSelf: "center",
    textAlign: "center",
    fontFamily: AppStyles.fonts.SF_FONT_BOLD,
    color: AppStyles.color.COLOR_WHITE,
    fontSize: 15.5,
  },
});

export default styles;
