import AppStyles from "app/config/styles";
import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: hp("100%"),
    width: wp("100%"),
    flexDirection: "column",
    backgroundColor: AppStyles.color.COLOR_BLACK,
    alignItems: "center",
    alignContent: "center",
  },
  backImage: {
    width: wp(9),
    height: wp(9),
    marginLeft: wp(8),
    marginTop: wp(6),
  },
  linearViewMain: {
    width: "100%",
    height: hp(10),
    flexDirection: "row",
  },
  viewOne: {
    height: "100%",
    flexDirection: "column",
    width: wp(46),
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginLeft: 35,
  },
  viewTwo: {
    height: wp(6),
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
  },
  textOne: {
    fontFamily: AppStyles.fonts.FONT_REGULAR,
    color: AppStyles.color.COLOR_WHITE,
    paddingLeft: 40,
    fontSize: hp(2.2),
  },
  viewThree: {
    height: "100%",
    width: wp(17),
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginLeft: 25,
  },
  imageOne: {
    width: wp(10),
    height: wp(10),
  },
  viewFour: {
    width: "98%",
    marginTop: 25,
    borderRadius: 10,
    height: hp(30),
    backgroundColor: "#282828",
  },
  viewFive: {
    flexDirection: "row",
    width: "80%",
    marginBottom: 5,
  },
  textTwo: {
    fontFamily: AppStyles.fonts.FONT_REGULAR,
    color: "#B2B2B2",
    paddingLeft: 20,
    marginTop: 15,
    fontSize: hp(1.9),
  },
  viewSix: {
    width: wp(25),
    justifyContent: "center",
    alignItems: "center",
    height: wp(7),
    borderRadius: 5,
    backgroundColor: "#0089FF",
    marginTop: 15,
    marginLeft: 130,
  },
  textThree: {
    fontFamily: AppStyles.fonts.FONT_REGULAR,
    color: AppStyles.color.COLOR_WHITE,
    fontSize: hp(1.9),
  },
  viewSeven: {
    flexDirection: "row",
    width: "80%",
    marginTop: 6,
    marginLeft: 20,
  },
  viewEight: {
    width: wp(11),
    justifyContent: "center",
    alignItems: "center",
    height: wp(11),
    borderRadius: 10,
    backgroundColor: "#39393B",
  },
  entypoOne: {
    alignSelf: "center",
  },
  imageFive: {
    width: wp(4.5),
    height: hp(2.5),
  },
  imageSix: {
    width: wp(5),
    height: hp(2.5),
  },
  textFour: {
    fontFamily: AppStyles.fonts.SF_FONT_REGULAR,
    color: "#FFFFFF",
    paddingLeft: 10,
    fontSize: hp(2.2),
  },
  textFive: {
    fontFamily: AppStyles.fonts.SF_FONT_REGULAR,
    color: "#808080",
    paddingLeft: 10,
    fontSize: hp(1.5),
  },
  imageTwo: {
    width: wp(22),
    height: wp(11),
    marginLeft: 45,
  },
  viewNine: {
    flexDirection: "row",
    width: "100%",
    marginTop: 10,
    marginLeft: 20,
  },
  imageThree: {
    width: wp(3),
    height: wp(3),
    marginTop: 5,
    marginLeft: 5,
  },
  viewTen: {
    borderBottomColor: "#0089FF",
    borderBottomWidth: 1,
    width: wp(70),
    height: wp(3),
  },
  imageFour: {
    width: wp(3),
    height: wp(3),
    marginTop: 5,
  },
  viewEleven: {
    flexDirection: "row",
    width: "45%",
    marginTop: 20,
    marginLeft: 20,
  },
  textSix: {
    fontFamily: AppStyles.fonts.SF_FONT_REGULAR,
    color: "#B2B2B2",
    fontSize: hp(1.8),
  },
  textSeven: {
    fontFamily: AppStyles.fonts.SF_FONT_REGULAR,
    color: "#808080",
    fontSize: hp(1.5),
  },
  textEight: {
    fontFamily: AppStyles.fonts.SF_FONT_REGULAR,
    color: "#B2B2B2",
    fontSize: hp(1.8),
    textAlign: "right",
  },
  viewTwelve: {
    borderBottomColor: "#FFB036",
    borderBottomWidth: 1,
    width: wp(70),
    height: wp(3),
  },
  viewThirteen: {
    borderBottomColor: "#50D86F",
    borderBottomWidth: 1,
    width: wp(70),
    height: wp(3),
  },
  viewFourteen: {
    borderStyle: "dotted",
    borderRadius: 1,
    borderBottomColor: "#D85050",
    borderBottomWidth: 1,
    width: wp(70),
    height: wp(3),
  },
  viewFifteen: {
    width: wp(25),
    justifyContent: "center",
    alignItems: "center",
    height: wp(7),
    borderRadius: 5,
    backgroundColor: "#D85050",
    marginTop: 15,
    marginLeft: 130,
  },
  viewSixteen: {
    width: wp(25),
    justifyContent: "center",
    alignItems: "center",
    height: wp(7),
    borderRadius: 5,
    backgroundColor: "#FFB036",
    marginTop: 15,
    marginLeft: 130,
  },
  viewSeventeen: {
    width: wp(25),
    justifyContent: "center",
    alignItems: "center",
    height: wp(7),
    borderRadius: 5,
    backgroundColor: "#50D86F",
    marginTop: 15,
    marginLeft: 130,
  },
  iosSpace: {
    width: wp(100),
    height: hp(6),
    backgroundColor: AppStyles.color.COLOR_BACKGROUND_BROWN,
  },
});

export default styles;
